@extends('layouts.app')
@section('title','Hospital Operations')
@section('content')
@php
    $role = auth()->user()->role;
    $canAdmin = in_array($role, ['admin', 'supervisor'], true);
    $operationsPayload = [...compact('hospitals', 'readiness', 'incidents', 'faults', 'transport', 'expiryItems', 'documents', 'role', 'canAdmin')];
@endphp
<div x-data='operationsPage(@json($operationsPayload))' x-init="init()" class="operations-page mx-auto min-w-0 max-w-7xl">
    <x-page-header title="Hospital Operations" description="Hospital readiness, emergency escalation and equipment fault management." eyebrow="Operational command centre" icon="activity">
        <x-slot:actions><button @click="enableAlerts()" class="gov-btn gov-btn-outline"><x-icon name="bell" class="h-4 w-4" />Enable alerts</button>@if(\App\Models\RolePermission::allows('view_reports'))<a href="{{ route('operations.pdf') }}" class="gov-btn gov-btn-primary"><x-icon name="download" class="h-4 w-4" />Executive PDF</a>@endif</x-slot:actions>
    </x-page-header>
    <nav aria-label="Operations sections" class="operations-nav-shell mb-4">
        <div class="operations-nav-core">
            <button type="button" @click="setTab('overview')" :aria-current="tab==='overview'?'page':null" class="operations-nav-item" :class="tab==='overview'&&'is-active'">
                <span class="operations-nav-icon"><x-icon name="activity" class="h-4 w-4" /></span><span><strong>Command Centre</strong><small>Operational readiness</small></span>
            </button>
            <button type="button" @click="setTab('emergencies')" :aria-current="tab==='emergencies'?'page':null" class="operations-nav-item" :class="tab==='emergencies'&&'is-active'">
                <span class="operations-nav-icon"><x-icon name="alert-triangle" class="h-4 w-4" /></span><span><strong>Emergencies</strong><small>Escalations</small></span><span x-show="incidents.filter(i=>['active','acknowledged'].includes(i.status)).length" class="operations-nav-count" x-text="incidents.filter(i=>['active','acknowledged'].includes(i.status)).length"></span>
            </button>
            <button type="button" @click="setTab('equipment')" :aria-current="tab==='equipment'?'page':null" class="operations-nav-item" :class="tab==='equipment'&&'is-active'">
                <span class="operations-nav-icon"><x-icon name="settings" class="h-4 w-4" /></span><span><strong>Equipment</strong><small>Faults & repair</small></span><span x-show="faults.filter(f=>!['operational','retired'].includes(f.status)).length" class="operations-nav-count" x-text="faults.filter(f=>!['operational','retired'].includes(f.status)).length"></span>
            </button>
        </div>
    </nav>

    <div class="mb-7 grid gap-3 rounded-2xl bg-secondary/45 p-3 sm:grid-cols-[minmax(0,1fr)_240px_auto]">
        <label class="relative"><span class="sr-only">Search operations</span><x-icon name="search" class="pointer-events-none absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" /><input x-model.debounce.250ms="searchQuery" class="gov-input pl-10" placeholder="Search emergencies and equipment"></label>
        <label><span class="sr-only">Hospital scope</span><select x-model="hospitalScope" class="gov-input"><option value="all" x-text="role==='admin'?'All accessible hospitals':role==='supervisor'?'My assigned atolls':'My assigned hospital'"></option><template x-for="h in hospitals" :key="h.id"><option :value="h.id" x-text="h.hospital_contact?.hospital_name||h.island?.name||'Hospital'"></option></template></select></label>
        <button type="button" @click="setTab('emergencies')" class="gov-btn gov-btn-danger"><x-icon name="alert-triangle" class="h-4 w-4" />Report issue</button>
    </div>

    <section x-show="tab==='overview'" class="operations-context-shell" aria-labelledby="operations-overview-title">
        <div class="operations-context-core"><div><p class="operations-context-kicker">Live command view</p><h2 id="operations-overview-title" class="operations-context-title">Facility readiness at a glance</h2><p class="operations-context-copy">A single operational picture of the hospitals in your assigned scope, prioritised by immediate risk.</p></div><div class="operations-context-metrics"><div class="operations-context-metric"><strong x-text="visibleReadiness().length"></strong><span>Facilities</span></div><div class="operations-context-metric"><strong class="text-amber-600" x-text="visibleReadiness().reduce((total,r)=>total+r.critical+r.warnings,0)"></strong><span>Open alerts</span></div></div></div>
    </section>
    <section x-show="tab==='emergencies'" class="operations-context-shell" aria-labelledby="operations-emergency-title">
        <div class="operations-context-core"><div><p class="operations-context-kicker">Emergency desk</p><h2 id="operations-emergency-title" class="operations-context-title">Escalations requiring coordinated response</h2><p class="operations-context-copy">Report critical events, confirm acknowledgement and follow the linked urgent task through resolution.</p></div><div class="operations-context-metrics"><div class="operations-context-metric"><strong class="text-red-600" x-text="incidents.filter(i=>i.status==='active').length"></strong><span>Active</span></div><div class="operations-context-metric"><strong class="text-amber-600" x-text="incidents.filter(i=>i.status==='acknowledged').length"></strong><span>Acknowledged</span></div></div></div>
    </section>
    <section x-show="tab==='equipment'" class="operations-context-shell" aria-labelledby="operations-equipment-title">
        <div class="operations-context-core"><div><p class="operations-context-kicker">Biomedical assets</p><h2 id="operations-equipment-title" class="operations-context-title">Equipment faults and repair oversight</h2><p class="operations-context-copy">Record failures, monitor repair progress and open linked tasks for accountable follow-up.</p></div><div class="operations-context-metrics"><div class="operations-context-metric"><strong x-text="faults.filter(f=>!['operational','retired'].includes(f.status)).length"></strong><span>Open faults</span></div><div class="operations-context-metric"><strong class="text-red-600" x-text="faults.filter(f=>f.severity==='critical'&&!['operational','retired'].includes(f.status)).length"></strong><span>Critical</span></div></div></div>
    </section>

    <section x-show="tab==='overview'" class="space-y-6">
        <div class="grid gap-3 sm:grid-cols-4">
            <div class="gov-card p-5"><p class="text-xs font-bold uppercase text-muted-foreground">Facilities</p><p class="mt-2 text-3xl font-black" x-text="visibleReadiness().length"></p></div>
            <div class="gov-card p-5"><p class="text-xs font-bold uppercase text-muted-foreground">Critical</p><p class="mt-2 text-3xl font-black text-red-600" x-text="visibleReadiness().filter(r=>r.status==='red').length"></p></div>
            <div class="gov-card p-5"><p class="text-xs font-bold uppercase text-muted-foreground">Attention</p><p class="mt-2 text-3xl font-black text-amber-600" x-text="visibleReadiness().filter(r=>r.status==='amber').length"></p></div>
            <div class="gov-card p-5"><p class="text-xs font-bold uppercase text-muted-foreground">Ready</p><p class="mt-2 text-3xl font-black text-emerald-600" x-text="visibleReadiness().filter(r=>r.status==='green').length"></p></div>
        </div>
        <div class="gov-card overflow-hidden p-5"><div class="mb-5"><h2 class="text-xl font-black">Maldives readiness map</h2><p class="text-sm text-muted-foreground">Facilities run north-to-south by atoll. Select a marker to see its readiness.</p></div><div class="grid gap-6 lg:grid-cols-[320px_1fr]"><div class="relative mx-auto h-[620px] w-full max-w-[280px] overflow-hidden rounded-[2rem] border border-emerald-100 bg-gradient-to-b from-cyan-50 via-teal-50 to-emerald-50"><div class="absolute bottom-5 left-1/2 top-5 w-px -translate-x-1/2 bg-gradient-to-b from-transparent via-teal-200 to-transparent"></div><template x-for="(r,index) in readiness" :key="r.hospital_id"><button @click="$refs['facility-'+r.hospital_id]?.scrollIntoView({behavior:'smooth',block:'center'})" class="group absolute -translate-x-1/2 -translate-y-1/2" :style="mapPosition(r,index)" :title="r.name"><span class="absolute inset-0 animate-ping rounded-full opacity-20" :class="r.status==='red'?'bg-red-500':r.status==='amber'?'bg-amber-500':'bg-emerald-500'"></span><span class="relative block h-4 w-4 rounded-full border-2 border-white shadow-lg" :class="r.status==='red'?'bg-red-500':r.status==='amber'?'bg-amber-500':'bg-emerald-500'"></span><span class="pointer-events-none absolute left-6 top-1/2 hidden w-max -translate-y-1/2 rounded-lg bg-slate-900 px-2 py-1 text-[10px] font-bold text-white shadow group-hover:block" x-text="r.island||r.atoll||r.name"></span></button></template><div x-show="!readiness.length" class="absolute inset-0 grid place-items-center p-8 text-center text-sm text-muted-foreground">Create hospital profiles to populate the map.</div><div class="absolute bottom-3 left-3 rounded-xl bg-white/85 px-3 py-2 text-[10px] font-bold uppercase tracking-wider text-teal-800 shadow-sm">Addu City</div><div class="absolute left-3 top-3 rounded-xl bg-white/85 px-3 py-2 text-[10px] font-bold uppercase tracking-wider text-teal-800 shadow-sm">Northern Maldives</div></div><div class="grid content-start gap-3 sm:grid-cols-2"><template x-for="r in readiness" :key="r.hospital_id"><article :x-ref="'facility-'+r.hospital_id" class="rounded-2xl border p-4" :class="r.status==='red'?'border-red-300 bg-red-50':r.status==='amber'?'border-amber-300 bg-amber-50':'border-emerald-200 bg-emerald-50'"><div class="flex items-start justify-between"><div><p class="font-black" x-text="r.name"></p><p class="text-xs text-muted-foreground" x-text="[r.island,r.atoll].filter(Boolean).join(' · ')"></p></div><span class="h-3 w-3 rounded-full" :class="r.status==='red'?'bg-red-500':r.status==='amber'?'bg-amber-500':'bg-emerald-500'"></span></div><p class="mt-3 text-xs font-semibold" x-text="r.critical+' critical · '+r.warnings+' warning(s)'"></p></article></template></div></div></div>
    </section>

    <section x-show="tab==='emergencies'" class="grid gap-5 lg:grid-cols-[360px_1fr]"><form @submit.prevent="save('incident')" class="gov-card h-fit space-y-3 p-5"><h2 class="text-lg font-black">Escalate emergency</h2><p class="text-xs leading-relaxed text-muted-foreground">This creates an operational incident and immediately alerts responsible officers. A follow-up task is optional.</p><select x-model="incidentForm.hospital_profile_id" required aria-label="Hospital" class="gov-input"><template x-for="h in hospitals"><option :value="h.id" x-text="h.hospital_contact?.hospital_name||h.island?.name"></option></template></select><input x-model="incidentForm.title" required aria-label="Emergency title" class="gov-input" placeholder="Emergency title"><select x-model="incidentForm.severity" aria-label="Severity" class="gov-input"><option value="high">High</option><option value="critical">Critical</option></select><textarea x-model="incidentForm.description" required rows="4" aria-label="Emergency details" class="gov-input" placeholder="Situation and immediate assistance required"></textarea><input type="file" accept="image/*,.pdf" aria-label="Supporting attachment" @change="upload($event,incidentForm,'attachment_url')" class="gov-input"><button :disabled="saving||uploading" class="gov-btn gov-btn-danger w-full">Report incident & alert officers</button></form><div class="space-y-3"><template x-for="i in incidents" :key="i.id"><article class="gov-card p-5"><div class="flex flex-wrap justify-between gap-3"><div><span class="badge" :class="badge(i.severity)" x-text="label(i.severity)"></span><h3 class="mt-2 text-lg font-black" x-text="i.title"></h3><p class="text-xs font-semibold text-primary" x-text="hospitalName(i)"></p></div><select :value="i.status" aria-label="Incident status" @change="update('incidents',i.id,{status:$event.target.value})" class="gov-input w-44"><option value="active">Active</option><option value="acknowledged">Acknowledged</option><option value="resolved">Resolved</option><option value="cancelled">Cancelled</option></select></div><p class="mt-3 text-sm text-muted-foreground" x-text="i.description"></p><div class="mt-4 flex items-center justify-between gap-3 rounded-xl bg-secondary/55 p-3"><div><p class="text-[10px] font-black uppercase tracking-[.12em] text-primary">Optional follow-up</p><p class="text-xs text-muted-foreground" x-text="i.task ? 'Linked task: '+label(i.task.status) : 'Create only when assigned work is needed'"></p></div><a x-show="i.task_id" :href="'/tasks?task='+i.task_id" class="gov-btn gov-btn-outline btn-sm shrink-0">Open task</a><button x-show="!i.task_id" @click="createActionTask('incident',i)" class="gov-btn gov-btn-primary btn-sm shrink-0">Create task</button></div></article></template></div></section>

    <section x-show="tab==='equipment'" class="grid gap-5 lg:grid-cols-[360px_1fr]"><form @submit.prevent="save('fault')" class="gov-card h-fit space-y-3 p-5"><h2 class="text-lg font-black">Report equipment fault</h2><p class="text-xs leading-relaxed text-muted-foreground">Record the equipment condition here. Create a separate follow-up task only when work must be assigned.</p><select x-model="faultForm.hospital_profile_id" aria-label="Hospital" class="gov-input"><template x-for="h in hospitals"><option :value="h.id" x-text="h.hospital_contact?.hospital_name||h.island?.name"></option></template></select><input x-model="faultForm.equipment_name" required aria-label="Equipment name" class="gov-input" placeholder="Equipment name"><input x-model="faultForm.asset_tag" aria-label="Asset tag" class="gov-input" placeholder="Asset tag"><select x-model="faultForm.severity" aria-label="Fault severity" class="gov-input"><option>low</option><option>medium</option><option>high</option><option>critical</option></select><textarea x-model="faultForm.description" required aria-label="Fault details" class="gov-input" placeholder="Fault details"></textarea><input type="file" accept="image/*" aria-label="Equipment photo" @change="upload($event,faultForm,'photo_url')" class="gov-input"><button class="gov-btn gov-btn-primary w-full">Report fault</button></form><div class="grid gap-3 sm:grid-cols-2"><template x-for="f in faults" :key="f.id"><article class="gov-card p-5"><div class="flex justify-between gap-2"><div><h3 class="font-black" x-text="f.equipment_name"></h3><p class="text-xs text-primary" x-text="hospitalName(f)"></p></div><span class="badge" :class="badge(f.severity)" x-text="label(f.severity)"></span></div><p class="mt-3 text-sm text-muted-foreground" x-text="f.description"></p><img x-show="f.photo_url" :src="f.photo_url" loading="lazy" class="mt-3 h-36 w-full rounded-xl object-cover"><div class="mt-3 flex items-center justify-between gap-3 rounded-xl bg-secondary/55 p-3"><div><p class="text-[10px] font-black uppercase tracking-[.12em] text-primary">Optional follow-up</p><p class="text-xs text-muted-foreground" x-text="f.task ? 'Linked task: '+label(f.task.status) : 'No task assigned'"></p></div><a x-show="f.task_id" :href="'/tasks?task='+f.task_id" class="gov-btn gov-btn-outline btn-sm shrink-0">Open task</a><button x-show="!f.task_id" @click="createActionTask('fault',f)" class="gov-btn gov-btn-primary btn-sm shrink-0">Create task</button></div><select :value="f.status" aria-label="Equipment status" @change="update('faults',f.id,{status:$event.target.value})" class="gov-input mt-3"><option value="reported">Reported</option><option value="assessing">Assessing</option><option value="repairing">Repairing</option><option value="operational">Operational</option><option value="retired">Retired</option></select></article></template></div></section>

    <section x-show="tab==='transport'" class="grid gap-5 lg:grid-cols-[360px_1fr]"><form @submit.prevent="save('transport')" class="gov-card h-fit space-y-3 p-5"><h2 class="text-lg font-black">Add ambulance or launch</h2><select x-model="transportForm.hospital_profile_id" class="gov-input"><template x-for="h in hospitals"><option :value="h.id" x-text="h.hospital_contact?.hospital_name||h.island?.name"></option></template></select><select x-model="transportForm.type" class="gov-input"><option value="ambulance">Ambulance</option><option value="launch">Launch</option></select><input x-model="transportForm.name" required class="gov-input" placeholder="Vehicle name"><input x-model="transportForm.registration_number" class="gov-input" placeholder="Registration number"><select x-model="transportForm.status" class="gov-input"><option value="operational">Operational</option><option value="unavailable">Unavailable</option><option value="maintenance">Under maintenance</option></select><textarea x-model="transportForm.unavailable_reason" class="gov-input" placeholder="Reason if unavailable"></textarea><label class="text-xs font-bold">Next service<input type="date" x-model="transportForm.next_service_date" class="gov-input mt-1"></label><button class="gov-btn gov-btn-primary w-full">Save asset</button></form><div class="grid gap-3 sm:grid-cols-2"><template x-for="a in transport" :key="a.id"><article class="gov-card p-5"><div class="flex justify-between"><div><p class="text-xs font-bold uppercase text-primary" x-text="a.type"></p><h3 class="text-lg font-black" x-text="a.name"></h3><p class="text-xs text-muted-foreground" x-text="hospitalName(a)"></p></div><span class="badge" :class="badge(a.status)" x-text="label(a.status)"></span></div><p class="mt-3 text-sm" x-text="a.unavailable_reason||'Ready for service'"></p><div x-show="a.status!=='operational'||a.task_id" class="mt-3 flex items-center justify-between gap-3 rounded-xl bg-primary/5 p-3"><span class="text-xs font-bold" x-text="a.task ? 'Task: '+label(a.task.status) : 'Maintenance action required'"></span><a x-show="a.task_id" :href="'/tasks?task='+a.task_id" class="gov-btn gov-btn-outline btn-sm">Open task</a><button x-show="!a.task_id" @click="createActionTask('transport',a)" class="gov-btn gov-btn-primary btn-sm">Create task</button></div><select :value="a.status" @change="update('transport',a.id,{status:$event.target.value})" class="gov-input mt-3"><option value="operational">Operational</option><option value="unavailable">Unavailable</option><option value="maintenance">Maintenance</option></select></article></template></div></section>

    <section x-show="tab==='expiry'" class="grid gap-5 lg:grid-cols-[360px_1fr]"><form @submit.prevent="save('expiry')" class="gov-card h-fit space-y-3 p-5"><h2 class="text-lg font-black">Track expiring item</h2><select x-model="expiryForm.hospital_profile_id" class="gov-input"><template x-for="h in hospitals"><option :value="h.id" x-text="h.hospital_contact?.hospital_name||h.island?.name"></option></template></select><select x-model="expiryForm.item_type" class="gov-input"><option value="medicine">Medicine</option><option value="reagent">Laboratory reagent</option><option value="licence">Licence</option><option value="equipment_service">Equipment service</option><option value="certification">Certification</option><option value="other">Other</option></select><input x-model="expiryForm.name" required class="gov-input" placeholder="Item name"><input x-model="expiryForm.reference_number" class="gov-input" placeholder="Batch / licence / reference"><label class="text-xs font-bold">Expiry or service date<input type="date" x-model="expiryForm.expiry_date" required class="gov-input mt-1"></label><input type="number" x-model="expiryForm.warning_days" min="1" max="365" class="gov-input" placeholder="Warning days"><button class="gov-btn gov-btn-primary w-full">Track item</button></form><div class="space-y-3"><template x-for="e in expiryItems" :key="e.id"><article class="gov-card flex flex-wrap items-center justify-between gap-4 p-5"><div><p class="text-xs font-bold uppercase text-primary" x-text="label(e.item_type)"></p><h3 class="font-black" x-text="e.name"></h3><p class="text-xs text-muted-foreground" x-text="hospitalName(e)"></p></div><div class="flex items-center gap-3"><div class="text-right"><p class="font-black" x-text="date(e.expiry_date)"></p><p class="text-xs font-bold" :class="new Date(e.expiry_date)<new Date()?'text-red-600':'text-amber-600'" x-text="expiryState(e)"></p></div><a x-show="e.task_id" :href="'/tasks?task='+e.task_id" class="gov-btn gov-btn-outline btn-sm">Open task</a><button x-show="!e.task_id" @click="createActionTask('expiry',e)" class="gov-btn gov-btn-primary btn-sm">Create task</button></div></article></template></div></section>

    <section x-show="tab==='documents'" class="grid gap-5 lg:grid-cols-[360px_1fr]"><form @submit.prevent="save('document')" class="gov-card h-fit space-y-3 p-5"><h2 class="text-lg font-black">Add controlled document</h2><select x-model="documentForm.hospital_profile_id" class="gov-input"><template x-for="h in hospitals"><option :value="h.id" x-text="h.hospital_contact?.hospital_name||h.island?.name"></option></template></select><select x-model="documentForm.category" class="gov-input"><option value="sop">SOP</option><option value="inspection">Inspection report</option><option value="licence">Licence</option><option value="emergency_plan">Emergency plan</option><option value="policy">Policy</option><option value="certificate">Certificate</option><option value="other">Other</option></select><input x-model="documentForm.title" required class="gov-input" placeholder="Document title"><input x-model="documentForm.version" class="gov-input" placeholder="Version"><label class="text-xs font-bold">Expiry date<input type="date" x-model="documentForm.expiry_date" class="gov-input mt-1"></label><input type="file" accept=".pdf,.doc,.docx,image/*" @change="upload($event,documentForm,'file_url')" required class="gov-input"><button :disabled="!documentForm.file_url" class="gov-btn gov-btn-primary w-full">Add document</button></form><div class="grid gap-3 sm:grid-cols-2"><template x-for="d in documents" :key="d.id"><article class="gov-card p-5"><p class="text-xs font-bold uppercase text-primary" x-text="label(d.category)"></p><h3 class="mt-1 font-black" x-text="d.title"></h3><p class="text-xs text-muted-foreground" x-text="hospitalName(d)"></p><p class="mt-3 text-sm" x-text="d.expiry_date?'Expires '+date(d.expiry_date):'No expiry date'"></p><div class="mt-4 flex gap-2"><a :href="d.file_url" target="_blank" class="gov-btn gov-btn-outline text-xs">Open</a><button @click="removeDocument(d)" class="gov-btn gov-btn-danger text-xs">Delete</button></div></article></template></div></section>
    @if($canAdmin)
    <section x-show="tab==='admin'" x-cloak class="space-y-5">
        <div class="gov-card overflow-hidden p-6 sm:p-8">
            <div class="max-w-2xl"><span class="badge bg-primary/10 text-primary">{{ ucfirst($role) }} access</span><h2 class="mt-3 text-2xl font-black">Operations administration</h2><p class="mt-2 text-sm text-muted-foreground">Manage the people, permissions and facility records that control this command centre. Operational records remain restricted to each user’s assigned hospitals and atolls.</p></div>
            <div class="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">
                <a href="{{ route('dashboard', ['tab' => 'users']) }}" class="group rounded-2xl bg-secondary/65 p-5 transition-all duration-500 ease-[cubic-bezier(.32,.72,0,1)] hover:-translate-y-1 hover:bg-primary/10"><span class="operations-nav-icon"><x-icon name="users" class="h-4 w-4" /></span><h3 class="mt-4 font-black">Users & roles</h3><p class="mt-1 text-xs text-muted-foreground">Accounts, roles and staff status</p></a>
                <a href="{{ route('role-permissions.index') }}" class="group rounded-2xl bg-secondary/65 p-5 transition-all duration-500 ease-[cubic-bezier(.32,.72,0,1)] hover:-translate-y-1 hover:bg-primary/10"><span class="operations-nav-icon"><x-icon name="shield" class="h-4 w-4" /></span><h3 class="mt-4 font-black">Permissions</h3><p class="mt-1 text-xs text-muted-foreground">Control page and action access</p></a>
                <a href="{{ route('dashboard', ['tab' => 'atolls']) }}" class="group rounded-2xl bg-secondary/65 p-5 transition-all duration-500 ease-[cubic-bezier(.32,.72,0,1)] hover:-translate-y-1 hover:bg-primary/10"><span class="operations-nav-icon"><x-icon name="map-pin" class="h-4 w-4" /></span><h3 class="mt-4 font-black">Atolls & islands</h3><p class="mt-1 text-xs text-muted-foreground">Regional ownership and assignments</p></a>
                <a href="{{ route('hospitals.index') }}" class="group rounded-2xl bg-secondary/65 p-5 transition-all duration-500 ease-[cubic-bezier(.32,.72,0,1)] hover:-translate-y-1 hover:bg-primary/10"><span class="operations-nav-icon"><x-icon name="hospital" class="h-4 w-4" /></span><h3 class="mt-4 font-black">Hospital profiles</h3><p class="mt-1 text-xs text-muted-foreground">Facility readiness and staffing data</p></a>
            </div>
        </div>
    </section>
    @endif
</div>
@endsection
